language: c

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - cmake
      - ruby-bundler
      - libssl-dev

script: cmake -DCMAKE_BUILD_TYPE=Debug . && make && bundle install --jobs=3 --retry=3 && bundle exec cucumber
